name: Control de Calidad mamasa-front

on:
  push:
    branches: [ main ]

jobs:
  verificacion:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar pruebas DevOps
        run: |
          echo "Iniciando pruebas..."
          node test.js
          echo "Pruebas ejecutadas correctamente"